CREATE TABLE fleet.remorque (
    id                              uuid            NOT NULL,
    immatriculation                 varchar(20)     NOT NULL,
    type                            varchar(30),
    carrosserie                     varchar(20)     NOT NULL,
    numero_parc                     varchar(50),
    vin                             varchar(50),
    marque                          varchar(50),
    modele                          varchar(100),
    annee_fabrication               integer,
    poids_vide_kg                   double precision,
    volume_utile_m3                 double precision NOT NULL DEFAULT 0,
    nb_positions_palettes           integer         NOT NULL DEFAULT 0,
    charge_utile_kg                 double precision NOT NULL DEFAULT 0,
    longueur_m                      double precision,
    largeur_m                       double precision,
    hauteur_m                       double precision,
    groupe_froid                    boolean         NOT NULL DEFAULT false,
    temperature_min                 double precision,
    temperature_max                 double precision,
    kilometrage                     integer         NOT NULL DEFAULT 0,
    heures_groupe_froid             integer         NOT NULL DEFAULT 0,
    statut                          varchar(20)     NOT NULL,
    date_premiere_mise_circulation  date,
    date_acquisition                date,
    date_mise_en_service            date,
    date_sortie                     date,
    motif_sortie                    varchar(100),
    kilometrage_sortie              integer,
    heures_groupe_froid_sortie      integer,
    created_at                      timestamptz     NOT NULL,
    created_by                      varchar(100)    NOT NULL,
    updated_at                      timestamptz     NOT NULL,
    updated_by                      varchar(100)    NOT NULL,
    version                         bigint          NOT NULL DEFAULT 0,
    CONSTRAINT pk_remorque PRIMARY KEY (id),
    CONSTRAINT uq_remorque_immat UNIQUE (immatriculation),
    CONSTRAINT ck_remorque_temperature_coherente CHECK (temperature_min IS NULL OR temperature_max IS NULL OR temperature_min <= temperature_max)
);

CREATE INDEX idx_remorque_statut ON fleet.remorque (statut);
